### ISSUE TITLE
[Bug] Binary in release 0.3 is the incorrect binary

### ISSUE THREAD

**Issue by Xelnoc** [RetroGamer8197/DOS-ASM#2]
command `ver` still reports version number 0.21, when running the latest release version number 0.3. Unsure if issue present on v2.2 as it has not been tested.

![image](https://github.com/RetroGamer8197/DOS-ASM/assets/109432268/edea757e-40c7-406e-b201-151de859879d)

**Comment by haraldsmeijers** [comment]
issue seems to be fixed in recent commit, however not shown in latest release. dev comment would be favourable.

**Comment by haraldsmeijers** [comment]
Binary contains release 0.21 rather than the source code, which correctly contains version 0.3
